
name: Generate ASCII ARTWORK

on:
  push:


jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Verify file contains 'dragon'
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt

      - name: Deploy (placeholder)
        run: echo "Deploying ..."
